<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="mahendrakodi-lambdatest-w7ghfwxdpta" failures="3" tests="3" name="Test on Edge" time="74.561" errors="0" timestamp="01 Jul 2023 13:42:31 GMT">
  <testcase classname="com.lambda.test.Tests" name="scenario2" time="8.992">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Values are not same expected [95] but found [96]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Values are not same expected [95] but found [96]
	at com.lambda.test.Tests.scenario2(Tests.java:58)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- scenario2 -->
  <testcase classname="com.lambda.test.Tests" name="scenario1" time="2.015">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Values are not same expected [95] but found [96]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Values are not same expected [95] but found [96]
	at com.lambda.test.Tests.scenario1(Tests.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- scenario1 -->
  <testcase classname="com.lambda.test.Tests" name="scenario3" time="9.256">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Values are not same expected [95] but found [96],
	expected [Please fill in the fields] but found [Please fill out this field.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Values are not same expected [95] but found [96],
	expected [Please fill in the fields] but found [Please fill out this field.]
	at com.lambda.test.Tests.scenario3(Tests.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- scenario3 -->
</testsuite> <!-- Test on Edge -->
